"""initial_tables

Revision ID: deb44c2b850c
Revises: 
Create Date: 2026-04-05 21:53:04.609964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb44c2b850c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mukellef',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unvan', sa.String(length=200), nullable=False),
    sa.Column('vkn', sa.String(length=10), nullable=False),
    sa.Column('vergi_dairesi', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mukellef_vkn'), 'mukellef', ['vkn'], unique=True)
    op.create_table('donem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mukellef_id', sa.Integer(), nullable=False),
    sa.Column('yil', sa.Integer(), nullable=False),
    sa.Column('ceyrek', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mukellef_id'], ['mukellef.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donem_mukellef_id'), 'donem', ['mukellef_id'], unique=False)
    op.create_table('calisma',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('donem_id', sa.Integer(), nullable=False),
    sa.Column('ticari_kar_zarar', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('kkeg', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('finansman_fonu', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('kar_mi_zarar_mi', sa.String(length=10), nullable=True),
    sa.Column('wizard_faz', sa.Integer(), nullable=False),
    sa.Column('wizard_cevaplari', sa.JSON(), nullable=True),
    sa.Column('istek_listesi', sa.JSON(), nullable=True),
    sa.Column('tamamlandi', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donem_id'], ['donem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calisma_donem_id'), 'calisma', ['donem_id'], unique=False)
    op.create_table('kalem_verisi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calisma_id', sa.Integer(), nullable=False),
    sa.Column('ic_kod', sa.String(length=100), nullable=False),
    sa.Column('girdi_verileri', sa.JSON(), nullable=True),
    sa.Column('hesap_sonucu', sa.JSON(), nullable=True),
    sa.Column('istisna_tutari', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('k_checklist_durumu', sa.JSON(), nullable=True),
    sa.Column('belge_durumu', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calisma_id'], ['calisma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kalem_verisi_calisma_id'), 'kalem_verisi', ['calisma_id'], unique=False)
    op.create_index(op.f('ix_kalem_verisi_ic_kod'), 'kalem_verisi', ['ic_kod'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kalem_verisi_ic_kod'), table_name='kalem_verisi')
    op.drop_index(op.f('ix_kalem_verisi_calisma_id'), table_name='kalem_verisi')
    op.drop_table('kalem_verisi')
    op.drop_index(op.f('ix_calisma_donem_id'), table_name='calisma')
    op.drop_table('calisma')
    op.drop_index(op.f('ix_donem_mukellef_id'), table_name='donem')
    op.drop_table('donem')
    op.drop_index(op.f('ix_mukellef_vkn'), table_name='mukellef')
    op.drop_table('mukellef')
    # ### end Alembic commands ###
